# generated by synth_and_time.tcl -- do not edit by hand
read_liberty /home/jack/tools/OpenROAD-flow-scripts/flow/platforms/sky130hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog /home/jack/projects/HW-RL-Environments/candidates/fifo_synth.v
link_design fifo

create_clock -name clk -period 5.0 [get_ports clk]
set_input_delay 0.5 -clock clk [all_inputs -no_clocks]
set_output_delay 0.5 -clock clk [all_outputs]

puts "===REPORT_CHECKS==="
report_checks -path_delay max
report_checks -path_delay min
puts "===WNS==="
report_wns
puts "===TNS==="
report_tns
puts "===WORST_SLACK==="
report_worst_slack
puts "===DONE==="
