// NEGATIVE CONTROL (d) -- a KNOWN-BAD DUT that must be CAUGHT, and it exists to
// prove the A4 check DISCRIMINATES rather than merely passes.
//
// A4 is an UPPER bound: at most MAX_READS reads outstanding. Its permissive half
// means a design accepting FEWER conforms, so the control cannot be
// capability-REDUCED -- dut2 accepts one at a time and is correct. This one is
// capability-INCREASED: the same design with room for six outstanding reads
// where the contract allows four, ports at full width and every other clause
// untouched.
//
// It must fail on A4 ALONE. A control that fails other clauses too would show
// the testbench rejects it, not that the A4 check works.
module dw_downsizer_over #(
    parameter int unsigned ADDR_W     = 32,
    parameter int unsigned ID_W       = 4,
    parameter int unsigned SLV_DATA_W = 64,   // upstream, wide
    parameter int unsigned MST_DATA_W = 16,   // downstream, narrow
    parameter int unsigned MAX_READS  = 4
) (
    input  logic clk_i,
    input  logic rst_ni,

    // ---- slave (upstream, WIDE) port ----
    input  logic [ID_W-1:0]          s_awid,
    input  logic [ADDR_W-1:0]        s_awaddr,
    input  logic [7:0]               s_awlen,
    input  logic [2:0]               s_awsize,
    input  logic [1:0]               s_awburst,
    input  logic                     s_awvalid,
    output logic                     s_awready,
    input  logic [SLV_DATA_W-1:0]    s_wdata,
    input  logic [SLV_DATA_W/8-1:0]  s_wstrb,
    input  logic                     s_wlast,
    input  logic                     s_wvalid,
    output logic                     s_wready,
    output logic [ID_W-1:0]          s_bid,
    output logic [1:0]               s_bresp,
    output logic                     s_bvalid,
    input  logic                     s_bready,
    input  logic [ID_W-1:0]          s_arid,
    input  logic [ADDR_W-1:0]        s_araddr,
    input  logic [7:0]               s_arlen,
    input  logic [2:0]               s_arsize,
    input  logic [1:0]               s_arburst,
    input  logic                     s_arvalid,
    output logic                     s_arready,
    output logic [ID_W-1:0]          s_rid,
    output logic [SLV_DATA_W-1:0]    s_rdata,
    output logic [1:0]               s_rresp,
    output logic                     s_rlast,
    output logic                     s_rvalid,
    input  logic                     s_rready,

    // ---- master (downstream, NARROW) port ----
    output logic [ID_W-1:0]          m_awid,
    output logic [ADDR_W-1:0]        m_awaddr,
    output logic [7:0]               m_awlen,
    output logic [2:0]               m_awsize,
    output logic [1:0]               m_awburst,
    output logic                     m_awvalid,
    input  logic                     m_awready,
    output logic [MST_DATA_W-1:0]    m_wdata,
    output logic [MST_DATA_W/8-1:0]  m_wstrb,
    output logic                     m_wlast,
    output logic                     m_wvalid,
    input  logic                     m_wready,
    input  logic [ID_W-1:0]          m_bid,
    input  logic [1:0]               m_bresp,
    input  logic                     m_bvalid,
    output logic                     m_bready,
    output logic [ID_W-1:0]          m_arid,
    output logic [ADDR_W-1:0]        m_araddr,
    output logic [7:0]               m_arlen,
    output logic [2:0]               m_arsize,
    output logic [1:0]               m_arburst,
    output logic                     m_arvalid,
    input  logic                     m_arready,
    input  logic [ID_W-1:0]          m_rid,
    input  logic [MST_DATA_W-1:0]    m_rdata,
    input  logic [1:0]               m_rresp,
    input  logic                     m_rlast,
    input  logic                     m_rvalid,
    output logic                     m_rready
);
  dw_downsizer_golden #(.ADDR_W(ADDR_W), .ID_W(ID_W), .SLV_DATA_W(SLV_DATA_W),
                        .MST_DATA_W(MST_DATA_W), .MAX_READS(6)) i_g (
    .clk_i,
    .rst_ni,
    .s_awid,
    .s_awaddr,
    .s_awlen,
    .s_awsize,
    .s_awburst,
    .s_awvalid,
    .s_awready,
    .s_wdata,
    .s_wstrb,
    .s_wlast,
    .s_wvalid,
    .s_wready,
    .s_bid,
    .s_bresp,
    .s_bvalid,
    .s_bready,
    .s_arid,
    .s_araddr,
    .s_arlen,
    .s_arsize,
    .s_arburst,
    .s_arvalid,
    .s_arready,
    .s_rid,
    .s_rdata,
    .s_rresp,
    .s_rlast,
    .s_rvalid,
    .s_rready,
    .m_awid,
    .m_awaddr,
    .m_awlen,
    .m_awsize,
    .m_awburst,
    .m_awvalid,
    .m_awready,
    .m_wdata,
    .m_wstrb,
    .m_wlast,
    .m_wvalid,
    .m_wready,
    .m_bid,
    .m_bresp,
    .m_bvalid,
    .m_bready,
    .m_arid,
    .m_araddr,
    .m_arlen,
    .m_arsize,
    .m_arburst,
    .m_arvalid,
    .m_arready,
    .m_rid,
    .m_rdata,
    .m_rresp,
    .m_rlast,
    .m_rvalid,
    .m_rready
  );
endmodule
