/* Generated by Yosys 0.67+137 (git sha1 41a4b5a03-dirty, Release, Clang /usr/bin/clang++ 21.1.8) */

(* top =  1  *)
(* src = "trivial_test.sv:1.1-13.10" *)
module trivial_test(clk, a, b, q);
  (* src = "trivial_test.sv:2.18-2.21" *)
  input clk;
  wire clk;
  (* src = "trivial_test.sv:3.18-3.19" *)
  input a;
  wire a;
  (* src = "trivial_test.sv:4.18-4.19" *)
  input b;
  wire b;
  (* src = "trivial_test.sv:5.18-5.19" *)
  output q;
  wire q;
  (* src = "trivial_test.sv:3.18-3.19" *)
  wire _0_;
  (* src = "trivial_test.sv:7.11-7.18" *)
  wire _1_;
  (* src = "trivial_test.sv:4.18-4.19" *)
  wire _2_;
  (* src = "trivial_test.sv:7.11-7.18" *)
  wire and_out;
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(_0_),
    .B(_2_),
    .X(_1_)
  );
  (* src = "trivial_test.sv:10.5-12.8" *)
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(clk),
    .D(and_out),
    .Q(q)
  );
  assign _0_ = a;
  assign _2_ = b;
  assign and_out = _1_;
endmodule
