// ---------------------------------------------------------------------------
// PORT MAP -- v_nw02 atop_filter
//
// This is the complete interface. It is the ONLY structural information you
// are given: there is no reference implementation, and none will be provided.
// Write your testbench against spec/atop_filter_spec.md and this file.
//
// The declaration below is extracted verbatim from the module under test, so
// the names, widths, directions and order are exactly what you must connect.
// The body is empty on purpose.
// ---------------------------------------------------------------------------
module atop_filter #(
  parameter int unsigned ID_W   = 4,
  parameter int unsigned ADDR_W = 32,
  parameter int unsigned DATA_W = 32,
  parameter int unsigned USER_W = 1
) (
  input  logic                clk_i,
  input  logic                rst_ni,
  // ---- slave port (upstream) ----
  input  logic [ID_W-1:0]     s_awid_i,
  input  logic [ADDR_W-1:0]   s_awaddr_i,
  input  logic [7:0]          s_awlen_i,
  input  logic [2:0]          s_awsize_i,
  input  logic [1:0]          s_awburst_i,
  input  logic                s_awlock_i,
  input  logic [3:0]          s_awcache_i,
  input  logic [2:0]          s_awprot_i,
  input  logic [3:0]          s_awqos_i,
  input  logic [3:0]          s_awregion_i,
  input  logic [5:0]          s_awatop_i,
  input  logic [USER_W-1:0]   s_awuser_i,
  input  logic                s_awvalid_i,
  output logic                s_awready_o,
  input  logic [DATA_W-1:0]   s_wdata_i,
  input  logic [DATA_W/8-1:0] s_wstrb_i,
  input  logic                s_wlast_i,
  input  logic [USER_W-1:0]   s_wuser_i,
  input  logic                s_wvalid_i,
  output logic                s_wready_o,
  output logic [ID_W-1:0]     s_bid_o,
  output logic [1:0]          s_bresp_o,
  output logic [USER_W-1:0]   s_buser_o,
  output logic                s_bvalid_o,
  input  logic                s_bready_i,
  input  logic [ID_W-1:0]     s_arid_i,
  input  logic [ADDR_W-1:0]   s_araddr_i,
  input  logic [7:0]          s_arlen_i,
  input  logic [2:0]          s_arsize_i,
  input  logic [1:0]          s_arburst_i,
  input  logic                s_arlock_i,
  input  logic [3:0]          s_arcache_i,
  input  logic [2:0]          s_arprot_i,
  input  logic [3:0]          s_arqos_i,
  input  logic [3:0]          s_arregion_i,
  input  logic [USER_W-1:0]   s_aruser_i,
  input  logic                s_arvalid_i,
  output logic                s_arready_o,
  output logic [ID_W-1:0]     s_rid_o,
  output logic [DATA_W-1:0]   s_rdata_o,
  output logic [1:0]          s_rresp_o,
  output logic                s_rlast_o,
  output logic [USER_W-1:0]   s_ruser_o,
  output logic                s_rvalid_o,
  input  logic                s_rready_i,
  // ---- master port (downstream) ----
  output logic [ID_W-1:0]     m_awid_o,
  output logic [ADDR_W-1:0]   m_awaddr_o,
  output logic [7:0]          m_awlen_o,
  output logic [2:0]          m_awsize_o,
  output logic [1:0]          m_awburst_o,
  output logic                m_awlock_o,
  output logic [3:0]          m_awcache_o,
  output logic [2:0]          m_awprot_o,
  output logic [3:0]          m_awqos_o,
  output logic [3:0]          m_awregion_o,
  output logic [5:0]          m_awatop_o,
  output logic [USER_W-1:0]   m_awuser_o,
  output logic                m_awvalid_o,
  input  logic                m_awready_i,
  output logic [DATA_W-1:0]   m_wdata_o,
  output logic [DATA_W/8-1:0] m_wstrb_o,
  output logic                m_wlast_o,
  output logic [USER_W-1:0]   m_wuser_o,
  output logic                m_wvalid_o,
  input  logic                m_wready_i,
  input  logic [ID_W-1:0]     m_bid_i,
  input  logic [1:0]          m_bresp_i,
  input  logic [USER_W-1:0]   m_buser_i,
  input  logic                m_bvalid_i,
  output logic                m_bready_o,
  output logic [ID_W-1:0]     m_arid_o,
  output logic [ADDR_W-1:0]   m_araddr_o,
  output logic [7:0]          m_arlen_o,
  output logic [2:0]          m_arsize_o,
  output logic [1:0]          m_arburst_o,
  output logic                m_arlock_o,
  output logic [3:0]          m_arcache_o,
  output logic [2:0]          m_arprot_o,
  output logic [3:0]          m_arqos_o,
  output logic [3:0]          m_arregion_o,
  output logic [USER_W-1:0]   m_aruser_o,
  output logic                m_arvalid_o,
  input  logic                m_arready_i,
  input  logic [ID_W-1:0]     m_rid_i,
  input  logic [DATA_W-1:0]   m_rdata_i,
  input  logic [1:0]          m_rresp_i,
  input  logic                m_rlast_i,
  input  logic [USER_W-1:0]   m_ruser_i,
  input  logic                m_rvalid_i,
  output logic                m_rready_o
);

  // no body -- see spec/atop_filter_spec.md for required behaviour
endmodule
