// =============================================================================
// tiny_core_tb.sv -- self-checking checker for `tiny_core` (ca_d08)
// =============================================================================
// NEVER SHIPPED TO A SUBMISSION.
//
// Expected values come ENTIRELY from tb/vectors/trace*.hex, generated by
// ref/model/rv32i_iss.py from the RISC-V ISA specification. This file contains
// NO instruction-set model: it does not compute what an instruction should do,
// it replays what the ISS said it did. Two implementations of the same subtle
// semantics would be two chances to make the same mistake.
//
// THE COMPARISON IS ORDER-BASED, NEVER CYCLE-STAMPED. The Nth retire is matched
// against the Nth trace entry, at whatever cycle it arrives. Nothing here
// asserts when a retire happens. A cycle-stamped compare is the fastest way to
// fail a correct design with a different pipeline depth, and it would show up
// as the second source failing in Step 5.
//
// The only place the checker decodes an instruction is COVERAGE ACCOUNTING --
// counting how many of each opcode class actually retired. That never
// contributes to the verdict.
//
// Build with --binary --timing --x-assign unique --x-initial unique, top module
// tiny_core_tb, -GIMEM_AW / -GDMEM_AW. Working directory must be the task
// directory so tb/vectors/* resolve. See NOTES.md.
//
// Final line is exactly one of:
//   TEST_RESULT: PASS
//   TEST_RESULT: FAIL: <reason>
// =============================================================================

`timescale 1ns/1ps

module tiny_core_tb;

    parameter int IMEM_AW = 10;        // 8 / 10 / 12
    parameter int DMEM_AW = 10;        // 8 / 10 / 12
    parameter int NUM_PROGS = 20;      // must match tb/vectors/MANIFEST.txt
    parameter int MAX_ERRORS_REPORTED = 20;
    parameter int MIN_CHECKS = 300;

    localparam int MAX_RET   = 256;                 // per program
    localparam int TRACE_W   = 6;                   // fields per retire entry
    localparam int IMEM_WORDS = 1 << IMEM_AW;
    localparam int DMEM_WORDS = 1 << DMEM_AW;

    logic        clk = 1'b0;
    logic        rst_n;
    logic [31:0] imem_addr, imem_rdata;
    logic        dmem_req, dmem_we;
    logic [31:0] dmem_addr, dmem_wdata, dmem_rdata;
    logic        retire_valid;
    logic [31:0] retire_pc;
    logic [4:0]  retire_rd;
    logic [31:0] retire_rd_val;
    logic        retire_is_store;
    logic [31:0] retire_store_addr, retire_store_data;

    tiny_core #(.IMEM_AW(IMEM_AW), .DMEM_AW(DMEM_AW)) dut (
        .clk(clk), .rst_n(rst_n),
        .imem_addr(imem_addr), .imem_rdata(imem_rdata),
        .dmem_req(dmem_req), .dmem_we(dmem_we), .dmem_addr(dmem_addr),
        .dmem_wdata(dmem_wdata), .dmem_rdata(dmem_rdata),
        .retire_valid(retire_valid), .retire_pc(retire_pc),
        .retire_rd(retire_rd), .retire_rd_val(retire_rd_val),
        .retire_is_store(retire_is_store),
        .retire_store_addr(retire_store_addr),
        .retire_store_data(retire_store_data));

    always #5 clk = ~clk;

    // ---------------- environment memories ----------------
    // Ideal and single-cycle, exactly as the spec promises: combinational read
    // on both ports, synchronous write on the data port, never a stall.
    logic [31:0] imem [0:IMEM_WORDS-1];
    logic [31:0] dmem [0:DMEM_WORDS-1];

    assign imem_rdata = imem[imem_addr[IMEM_AW+1:2]];
    assign dmem_rdata = dmem[dmem_addr[DMEM_AW+1:2]];

    always_ff @(posedge clk)
        if (rst_n && dmem_req && dmem_we)
            dmem[dmem_addr[DMEM_AW+1:2]] <= dmem_wdata;

    // ---------------- bookkeeping ----------------
    int    errors = 0, checks = 0;
    string fail_reason = "", phase = "init";

    task automatic note_fail(input string why);
        errors++;
        if (fail_reason == "") fail_reason = why;
        if (errors <= MAX_ERRORS_REPORTED)
            $display("[FAIL] t=%0t phase=%s : %s", $time, phase, why);
        else if (errors == MAX_ERRORS_REPORTED + 1)
            $display("[FAIL] ... further failures suppressed");
    endtask

    // ---------------- golden trace ----------------
    // Six whitespace-separated hex tokens per retire, read flat:
    //   [6n+0]=pc [6n+1]=rd [6n+2]=rd_val [6n+3]=is_store
    //   [6n+4]=store_addr [6n+5]=store_data
    logic [31:0] trace   [0:TRACE_W*MAX_RET-1];
    logic [31:0] n_ret   [0:NUM_PROGS-1];

    // Comparison temporaries. Declared at module scope rather than as
    // `automatic` inside the monitor: Icarus does not support overriding the
    // default variable lifetime, and the harness must build under both
    // simulators. The monitor is the only writer, so scope costs nothing here.
    int          m_base;
    logic [31:0] e_pc, e_val, e_sa, e_sd, m_ir;
    logic [4:0]  e_rd;
    logic        e_st;

    int exp_retires;      // for the program under test
    int got_retires;
    bit checking;         // monitor active only inside a program run

    // ---------------- coverage ----------------
    int cov_alu = 0, cov_shift = 0, cov_load = 0, cov_store = 0;
    int cov_br_taken = 0, cov_br_ntaken = 0, cov_jal = 0, cov_jalr = 0;
    int cov_lui = 0, cov_auipc = 0;
    int cov_x0_write = 0;      // instruction encoding rd == x0 that still retires
    int cov_sra_neg = 0;       // sra with a negative operand
    int cov_progs = 0;
    int cov_maxret = 0;

    // ---------------- retire monitor ----------------
    // Order-based comparison. Nothing here looks at the cycle number.
    always_ff @(posedge clk) begin
        if (rst_n && checking && retire_valid) begin
            if (got_retires >= exp_retires) begin
                // extra retires beyond the trace are not an error: the program
                // ends in an architectural self-loop and the core keeps running.
            end else begin
                m_base = TRACE_W * got_retires;
                e_pc   = trace[m_base+0];
                e_rd   = trace[m_base+1][4:0];
                e_val  = trace[m_base+2];
                e_st   = trace[m_base+3][0];
                e_sa   = trace[m_base+4];
                e_sd   = trace[m_base+5];
                m_ir   = imem[e_pc[IMEM_AW+1:2]];

                checks++;
                if (retire_pc !== e_pc)
                    note_fail($sformatf("retire %0d: pc=0x%08h expected 0x%08h",
                                        got_retires, retire_pc, e_pc));
                if (retire_rd !== e_rd)
                    note_fail($sformatf("retire %0d (pc 0x%08h): rd=%0d expected %0d",
                                        got_retires, e_pc, retire_rd, e_rd));
                if (retire_rd_val !== e_val)
                    note_fail($sformatf("retire %0d (pc 0x%08h): rd_val=0x%08h expected 0x%08h",
                                        got_retires, e_pc, retire_rd_val, e_val));
                if (retire_is_store !== e_st)
                    note_fail($sformatf("retire %0d (pc 0x%08h): is_store=%0b expected %0b",
                                        got_retires, e_pc, retire_is_store, e_st));
                if (e_st) begin
                    if (retire_store_addr !== e_sa)
                        note_fail($sformatf("retire %0d (pc 0x%08h): store addr=0x%08h expected 0x%08h",
                                            got_retires, e_pc, retire_store_addr, e_sa));
                    if (retire_store_data !== e_sd)
                        note_fail($sformatf("retire %0d (pc 0x%08h): store data=0x%08h expected 0x%08h",
                                            got_retires, e_pc, retire_store_data, e_sd));
                end

                // ---- coverage only, never graded -------------------------
                case (m_ir[6:0])
                    7'h37: cov_lui++;
                    7'h17: cov_auipc++;
                    7'h6F: cov_jal++;
                    7'h67: cov_jalr++;
                    7'h03: cov_load++;
                    7'h23: cov_store++;
                    7'h63: begin
                        // taken iff the NEXT retire's pc is not pc+4
                        if (got_retires + 1 < exp_retires) begin
                            if (trace[TRACE_W*(got_retires+1)] !== e_pc + 32'd4)
                                cov_br_taken++;
                            else cov_br_ntaken++;
                        end
                    end
                    7'h33: begin
                        if (m_ir[14:12] == 3'b001 || m_ir[14:12] == 3'b101) begin
                            cov_shift++;
                            if (m_ir[31:25] == 7'h20) cov_sra_neg++;
                        end else cov_alu++;
                    end
                    default: cov_alu++;
                endcase
                if (m_ir[11:7] == 5'd0 && m_ir[6:0] != 7'h63 && m_ir[6:0] != 7'h23)
                    cov_x0_write++;

                got_retires++;
            end
        end
    end

    // ---------------- program runner ----------------
    int p, guard, limit;

    task automatic clear_mem();
        for (int i = 0; i < IMEM_WORDS; i++) imem[i] = 32'd0;
        for (int i = 0; i < DMEM_WORDS; i++) dmem[i] = 32'd0;
    endtask

    initial begin
        // ---- illegal-parameter guard -----------------------------------
        if (IMEM_AW != 8 && IMEM_AW != 10 && IMEM_AW != 12) begin
            $display("TEST_RESULT: FAIL: illegal IMEM_AW=%0d (legal: 8,10,12)", IMEM_AW); $finish;
        end
        if (DMEM_AW != 8 && DMEM_AW != 10 && DMEM_AW != 12) begin
            $display("TEST_RESULT: FAIL: illegal DMEM_AW=%0d (legal: 8,10,12)", DMEM_AW); $finish;
        end

        $readmemh("tb/vectors/retires.hex", n_ret);
        if (n_ret[0] === 32'hxxxx_xxxx) begin
            $display("TEST_RESULT: FAIL: could not load tb/vectors/retires.hex (wrong working directory?)");
            $finish;
        end

        checking = 1'b0;
        rst_n = 1'b0;

        for (p = 0; p < NUM_PROGS; p++) begin
            phase = $sformatf("P%0d", p);

            // fresh machine state for every program: the ISS starts each one
            // with zeroed memory, so the checker must too.
            checking = 1'b0;
            rst_n = 1'b0;
            clear_mem();
            for (int i = 0; i < TRACE_W*MAX_RET; i++) trace[i] = 32'd0;
            $readmemh($sformatf("tb/vectors/prog%02d.hex", p), imem);
            $readmemh($sformatf("tb/vectors/trace%02d.hex", p), trace);
            exp_retires = int'(n_ret[p]);
            got_retires = 0;
            if (exp_retires > MAX_RET) begin
                $display("TEST_RESULT: FAIL: program %0d needs %0d retires, MAX_RET=%0d",
                         p, exp_retires, MAX_RET);
                $finish;
            end

            repeat (4) begin @(posedge clk); #1; end
            if (retire_valid !== 1'b0) note_fail("retire_valid asserted during reset (R9)");
            rst_n = 1'b1;
            // Deliberately NOT checking retire_valid here. The spec constrains
            // retire_valid only while rst_n is low; when the first retire
            // arrives afterwards is a pipeline-depth artifact and checking it
            // would fail a correct single-cycle core.
            checking = 1'b1;
            @(posedge clk); #1;

            // liveness bound from the spec: 64*N + 256 cycles
            limit = 64*exp_retires + 256;
            guard = 0;
            while (got_retires < exp_retires && guard < limit) begin
                @(posedge clk); #1; guard++;
            end
            checking = 1'b0;
            if (got_retires < exp_retires)
                note_fail($sformatf("program %0d retired %0d of %0d within %0d cycles (liveness)",
                                    p, got_retires, exp_retires, limit));
            else begin
                cov_progs++;
                if (exp_retires > cov_maxret) cov_maxret = exp_retires;
            end
        end

        // ------------------------------------------------------------------
        phase = "final";
        rst_n = 1'b0;
        repeat (2) begin @(posedge clk); #1; end

        $display("METRIC: programs=%0d retires_checked=%0d", cov_progs, checks);

        begin
            int cov_missing;
            cov_missing = 0;
            $display("// coverage: alu=%0d shift=%0d load=%0d store=%0d lui=%0d auipc=%0d",
                     cov_alu, cov_shift, cov_load, cov_store, cov_lui, cov_auipc);
            $display("// coverage: br_taken=%0d br_ntaken=%0d jal=%0d jalr=%0d x0_write=%0d sra=%0d",
                     cov_br_taken, cov_br_ntaken, cov_jal, cov_jalr, cov_x0_write, cov_sra_neg);
            $display("// coverage: programs=%0d longest=%0d retires", cov_progs, cov_maxret);
            if (cov_alu       == 0) begin cov_missing++; $display("// COVERAGE HOLE: no ALU instruction retired"); end
            if (cov_shift     == 0) begin cov_missing++; $display("// COVERAGE HOLE: no shift retired"); end
            if (cov_load      == 0) begin cov_missing++; $display("// COVERAGE HOLE: no load retired"); end
            if (cov_store     == 0) begin cov_missing++; $display("// COVERAGE HOLE: no store retired"); end
            if (cov_lui       == 0) begin cov_missing++; $display("// COVERAGE HOLE: no lui retired"); end
            if (cov_auipc     == 0) begin cov_missing++; $display("// COVERAGE HOLE: no auipc retired"); end
            if (cov_jal       == 0) begin cov_missing++; $display("// COVERAGE HOLE: no jal retired"); end
            if (cov_jalr      == 0) begin cov_missing++; $display("// COVERAGE HOLE: no jalr retired"); end
            if (cov_br_taken  == 0) begin cov_missing++; $display("// COVERAGE HOLE: no taken branch"); end
            if (cov_br_ntaken == 0) begin cov_missing++; $display("// COVERAGE HOLE: no not-taken branch"); end
            if (cov_x0_write  == 0) begin cov_missing++; $display("// COVERAGE HOLE: no instruction encoding rd==x0"); end
            if (cov_sra_neg   == 0) begin cov_missing++; $display("// COVERAGE HOLE: no arithmetic right shift"); end
            if (cov_progs != NUM_PROGS) begin cov_missing++; $display("// COVERAGE HOLE: only %0d of %0d programs completed", cov_progs, NUM_PROGS); end
            if (cov_missing > 0)
                note_fail($sformatf("%0d coverage holes -- run did not exercise the target hazards",
                                    cov_missing));
        end

        if (checks < MIN_CHECKS)
            note_fail($sformatf("insufficient coverage: only %0d retires checked", checks));

        if (errors == 0) $display("TEST_RESULT: PASS");
        else $display("TEST_RESULT: FAIL: %s (%0d failing checks of %0d)",
                      fail_reason, errors, checks);
        $finish;
    end

    initial begin
        #40_000_000;
        $display("// watchdog fired in phase=%s got_retires=%0d exp=%0d", phase, got_retires, exp_retires);
        $display("TEST_RESULT: FAIL: timeout -- checker did not complete (phase=%s)", phase);
        $finish;
    end

endmodule
