// =============================================================================
// int8_requant_tb.sv -- self-checking checker for `int8_requant` (ai_d01)
// =============================================================================
// NEVER SHIPPED TO A SUBMISSION.
//
// Expected values come ENTIRELY from tb/vectors/expected.hex, generated by
// ref/model/int8_requant_model.py from the arithmetic in the spec header. This
// file contains NO independent arithmetic model -- it does not re-derive the
// requantisation, it replays it. That is deliberate: two implementations of the
// same subtle rounding rule would be two chances to make the same mistake.
//
// flags.hex is used for COVERAGE ACCOUNTING ONLY, never for grading.
//
// Run (see NOTES.md for the exact invocation; it is not repeated verbatim here
// because a comment beginning with the simulator's own name is parsed as a
// pragma): build with --binary --timing --x-assign unique --x-initial unique,
// top module int8_requant_tb, -GLANES=<1|2|4|8>.
// The working directory must be the task directory so tb/vectors/*.hex resolve.
//
// Final line is exactly one of:
//   TEST_RESULT: PASS
//   TEST_RESULT: FAIL: <reason>
// =============================================================================

`timescale 1ns/1ps

module int8_requant_tb;

    // ---------------- configuration ----------------
    parameter int LANES               = 4;      // 1 / 2 / 4 / 8
    parameter int VEC_COUNT           =     2060;   // must match vectors/MANIFEST.txt
    parameter int MAX_ERRORS_REPORTED = 20;
    parameter int MIN_CHECKS          = 800;
    parameter int SOAK_BEATS          = 2500;

    localparam int MAX_BEATS = 16384;
    localparam int LAT_LIMIT = 64;              // spec: output within 64 cycles

    // ---------------- DUT connections ----------------
    logic                clk = 1'b0;
    logic                rst_n;
    logic                in_valid, in_ready;
    logic [LANES*32-1:0] acc, mult;
    logic [LANES*5-1:0]  shift;
    logic [LANES*8-1:0]  zp;
    logic                out_valid, out_ready;
    logic [LANES*8-1:0]  result;

    // out_ready driving. bp_auto=1 -> free-running weighted backpressure, which
    // keeps toggling so a design with only one buffer slot always eventually
    // drains and can accept the next beat. bp_auto=0 -> directed control via
    // out_ready_man, used where a phase needs an exact stall pattern.
    // Nothing here may make forward progress depend on the DUT having capacity
    // greater than one: the spec constrains no buffering whatsoever.
    bit  bp_auto      = 1'b0;
    int  bp_weight    = 0;          // percent of cycles out_ready is LOW
    bit  out_ready_man = 1'b1;
    bit  out_ready_auto = 1'b1;
    assign out_ready = bp_auto ? out_ready_auto : out_ready_man;

    int8_requant #(.LANES(LANES)) dut (
        .clk(clk), .rst_n(rst_n),
        .in_valid(in_valid), .in_ready(in_ready),
        .acc(acc), .mult(mult), .shift(shift), .zp(zp),
        .out_valid(out_valid), .out_ready(out_ready), .result(result)
    );

    always #5 clk = ~clk;

    // ---------------- bookkeeping ----------------
    int    errors = 0;
    int    checks = 0;
    string fail_reason = "";
    string phase = "init";

    task automatic note_fail(input string why);
        errors++;
        if (fail_reason == "") fail_reason = why;
        if (errors <= MAX_ERRORS_REPORTED)
            $display("[FAIL] t=%0t phase=%s : %s", $time, phase, why);
        else if (errors == MAX_ERRORS_REPORTED + 1)
            $display("[FAIL] ... further failures suppressed");
    endtask

    // ---------------- committed golden vectors ----------------
    logic [31:0] v_acc  [0:VEC_COUNT-1];
    logic [31:0] v_mult [0:VEC_COUNT-1];
    logic [7:0]  v_shift[0:VEC_COUNT-1];
    logic [7:0]  v_zp   [0:VEC_COUNT-1];
    logic [7:0]  v_exp  [0:VEC_COUNT-1];
    logic [7:0]  v_flag [0:VEC_COUNT-1];

    // ---------------- per-beat expectations ----------------
    // Filled when a beat is ACCEPTED, drained when a result is accepted.
    logic [LANES*8-1:0] beat_exp  [0:MAX_BEATS-1];
    logic [LANES*8-1:0] beat_flag [0:MAX_BEATS-1];  // OR of lane flags
    int                 beat_vec0 [0:MAX_BEATS-1];  // first vector idx, for msgs
    int beats_sent = 0;
    int beats_recv = 0;

    // Staged expectation for whatever is currently presented on the input
    // ports. The MONITOR commits it into beat_exp[] when it observes the real
    // in_valid && in_ready handshake -- the driver never records a beat itself.
    // Driver-side accounting is what desynced the scoreboard: it had to guess
    // which edge would transfer. Observing the handshake cannot guess wrong.
    logic [LANES*8-1:0] stage_e, stage_f;
    int                 stage_v0;

    // ---------------- coverage counters ----------------
    int cov_clamp_hi = 0, cov_clamp_lo = 0;
    int cov_tie1 = 0, cov_tie2 = 0;
    int cov_sh0 = 0, cov_sh31 = 0;
    int cov_bp = 0;          // out_valid held under out_ready==0
    int cov_in_stall = 0;    // in_valid held under in_ready==0
    int cov_reset_mid = 0;   // reset with work in flight
    int cov_b2b = 0;         // back-to-back accept on consecutive cycles
    int cov_idle_gap = 0;    // in_valid deasserted between beats

    // observed latency, reported as METRIC only -- never gates the verdict
    int lat_min = 1_000_000, lat_max = 0;
    int accept_time [0:MAX_BEATS-1];
    // Time the beat became AVAILABLE (out_valid high for it). The spec bounds
    // latency to availability, NOT to acceptance: cycles spent waiting because
    // the checker itself is holding out_ready low are backpressure, not DUT
    // latency, and must not be charged against the DUT.
    int avail_time [0:MAX_BEATS-1];

    // ---------------- output monitor ----------------
    // Checks every accepted output beat against the committed expectation, in
    // order. Ordering (spec H4) is enforced by construction: beat N out is
    // compared against beat N in.
    logic prev_out_valid, prev_out_ready;
    logic [LANES*8-1:0] prev_result;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            prev_out_valid <= 1'b0;
            prev_out_ready <= 1'b0;
        end else begin
            // ---- H3: stability under backpressure --------------------------
            // A beat that was valid at the previous edge and NOT accepted there
            // (out_ready low AT THAT EDGE) must still be valid and unchanged now.
            if (prev_out_valid && !prev_out_ready) begin
                cov_bp++;
                if (!out_valid)
                    note_fail("out_valid dropped while the beat was unaccepted (H3)");
                else if (result !== prev_result)
                    note_fail($sformatf(
                        "result changed under backpressure: 0x%0h -> 0x%0h (H3)",
                        prev_result, result));
            end

            // ---- accepted INPUT beat: commit its expectation ---------------
            if (in_valid && in_ready) begin
                beat_exp   [beats_sent] = stage_e;
                beat_flag  [beats_sent] = stage_f;
                beat_vec0  [beats_sent] = stage_v0;
                accept_time[beats_sent] = int'($time/10);
                avail_time [beats_sent] = -1;
                beats_sent++;
            end

            // ---- first cycle this beat is visible: stamp availability -----
            if (out_valid && beats_recv < beats_sent && avail_time[beats_recv] < 0)
                avail_time[beats_recv] = int'($time/10);

            // ---- accepted output beat --------------------------------------
            if (out_valid && out_ready) begin
                checks++;
                if (beats_recv >= beats_sent) begin
                    note_fail($sformatf(
                        "output beat %0d appeared with only %0d beats accepted (H5)",
                        beats_recv, beats_sent));
                end else begin
                    if (result !== beat_exp[beats_recv]) begin
                        note_fail($sformatf(
                            "beat %0d (vec %0d): result=0x%0h expected=0x%0h",
                            beats_recv, beat_vec0[beats_recv],
                            result, beat_exp[beats_recv]));
                    end
                    // credit coverage from the beat that actually retired
                    for (int L = 0; L < LANES; L++) begin
                        logic [7:0] f;
                        f = beat_flag[beats_recv][L*8 +: 8];
                        if (f[0]) cov_clamp_hi++;
                        if (f[1]) cov_clamp_lo++;
                        if (f[2]) cov_tie1++;
                        if (f[3]) cov_tie2++;
                        if (f[4]) cov_sh0++;
                        if (f[5]) cov_sh31++;
                    end
                    begin
                        int lat;
                        if (avail_time[beats_recv] < 0)
                            avail_time[beats_recv] = int'($time/10);
                        lat = avail_time[beats_recv] - accept_time[beats_recv];
                        if (lat < lat_min) lat_min = lat;
                        if (lat > lat_max) lat_max = lat;
                        if (lat > LAT_LIMIT)
                            note_fail($sformatf(
                                "beat %0d latency-to-available %0d cycles exceeds bound %0d",
                                beats_recv, lat, LAT_LIMIT));
                    end
                    beats_recv++;
                end
            end

            prev_out_valid <= out_valid;
            prev_out_ready <= out_ready;
            prev_result    <= result;
        end
    end

    // input-stall coverage
    always_ff @(posedge clk) begin
        if (rst_n && in_valid && !in_ready) cov_in_stall++;
    end

    // free-running backpressure generator
    always_ff @(posedge clk) begin
        out_ready_auto <= (($urandom_range(0,99)) >= bp_weight);
    end

    // ---------------- stimulus helpers ----------------
    int vec_ptr = 0;

    // Load LANES consecutive vectors (wrapping) into the input ports and record
    // the expectation. Does NOT drive the handshake.
    task automatic stage_beat(input int base);
        logic [LANES*8-1:0] e, f;
        e = '0; f = '0;
        for (int L = 0; L < LANES; L++) begin
            int idx;
            idx = (base + L) % VEC_COUNT;
            acc  [L*32 +: 32] = v_acc  [idx];
            mult [L*32 +: 32] = v_mult [idx];
            shift[L*5  +:  5] = v_shift[idx][4:0];
            zp   [L*8  +:  8] = v_zp   [idx];
            e    [L*8  +:  8] = v_exp  [idx];
            f    [L*8  +:  8] = v_flag [idx];
        end
        stage_e  = e;
        stage_f  = f;
        stage_v0 = base % VEC_COUNT;
    endtask

    // Offer one beat and hold it until accepted (spec H2 permits relying on
    // stability, so the checker must actually provide it).
    //
    // in_ready is sampled at NEGEDGE. It is combinational off registered state,
    // so its negedge value is exactly its value at the upcoming posedge -- which
    // is the edge that actually transfers the beat. Sampling just after a
    // posedge instead would read the value for the FOLLOWING cycle and
    // mis-align every beat with its expectation.
    task automatic send_beat(input int base, input int max_wait);
        int waited, target;
        stage_beat(base);
        in_valid = 1'b1;
        target = beats_sent + 1;
        waited = 0;
        while (beats_sent < target && waited < max_wait) begin
            @(posedge clk);
            #1;                 // drive only AFTER the edge has been sampled
            waited++;
        end
        in_valid = 1'b0;
        if (beats_sent < target)
            note_fail($sformatf("beat not accepted within %0d cycles", max_wait));
    endtask

    task automatic idle_cycles(input int n);
        in_valid = 1'b0;
        for (int i = 0; i < n; i++) begin @(posedge clk); #1; end
    endtask

    // stage_beat writes beat_exp[beats_sent]; send_beat increments beats_sent
    // only once the transfer is guaranteed, so the expectation array and the
    // DUT's output stream stay index-aligned even when a send times out.

    task automatic do_reset();
        in_valid = 1'b0; bp_auto = 1'b0; out_ready_man = 1'b1;
        acc = '0; mult = '0; shift = '0; zp = '0;
        rst_n = 1'b0;
        repeat (3) begin @(posedge clk); #1; end
        if (out_valid !== 1'b0) note_fail("out_valid non-zero during reset (R1)");
        rst_n = 1'b1;
        @(posedge clk);
        #1;
        if (out_valid !== 1'b0) note_fail("out_valid non-zero in first cycle after reset (R1)");
        beats_sent = 0; beats_recv = 0;
        for (int i = 0; i < MAX_BEATS; i++) avail_time[i] = -1;
    endtask

    // ---------------- drain ----------------
    task automatic drain(input int max_wait);
        int waited;
        waited = 0;
        out_ready_man = 1'b1;
        while (beats_recv < beats_sent && waited < max_wait) begin
            @(posedge clk);
            #1;
            waited++;
        end
        if (beats_recv < beats_sent)
            note_fail($sformatf("drain timeout: %0d of %0d beats returned",
                                beats_recv, beats_sent));
    endtask

    // A phase must end with every accepted beat returned. Checking this at each
    // boundary means a desync is reported where it happens instead of silently
    // shifting every comparison in every later phase by one.
    task automatic sync_check(input string tag);
        if (beats_sent != beats_recv)
            note_fail($sformatf("%s ended desynced: %0d beats accepted, %0d returned",
                                tag, beats_sent, beats_recv));
    endtask

    // ---------------- main ----------------

    int base;

    initial begin
        // ---- illegal-parameter guard (bad benchmark config, not a DUT bug) --
        if (LANES != 1 && LANES != 2 && LANES != 4 && LANES != 8) begin
            $display("TEST_RESULT: FAIL: illegal LANES=%0d (legal: 1,2,4,8)", LANES);
            $finish;
        end
        if (VEC_COUNT < 64) begin
            $display("TEST_RESULT: FAIL: illegal VEC_COUNT=%0d", VEC_COUNT);
            $finish;
        end

        $readmemh("tb/vectors/acc.hex",      v_acc);
        $readmemh("tb/vectors/mult.hex",     v_mult);
        $readmemh("tb/vectors/shift.hex",    v_shift);
        $readmemh("tb/vectors/zp.hex",       v_zp);
        $readmemh("tb/vectors/expected.hex", v_exp);
        $readmemh("tb/vectors/flags.hex",    v_flag);

        if (v_exp[VEC_COUNT-1] === 8'hxx || v_acc[VEC_COUNT-1] === 32'hxxxx_xxxx) begin
            $display("TEST_RESULT: FAIL: vector load short -- VEC_COUNT=%0d exceeds file length",
                     VEC_COUNT);
            $finish;
        end


        // ------------------------------------------------------------------
        // D1: reset semantics
        // ------------------------------------------------------------------
        phase = "D1-reset";
        do_reset();
        idle_cycles(3);
        if (out_valid !== 1'b0) note_fail("out_valid asserted with no input offered (R1)");

        // ------------------------------------------------------------------
        // D2: one beat, no backpressure -- proves the basic path
        // ------------------------------------------------------------------
        phase = "D2-single";
        out_ready_man = 1'b1;
        send_beat(0, LAT_LIMIT);
        drain(LAT_LIMIT * 4);
        sync_check("D2");

        // ------------------------------------------------------------------
        // D3: every directed vector at full rate. These are the arithmetic
        //     hazards: saturation both ways, step-1 ties, step-2 ties,
        //     shift 0 and 31, zero-point extremes.
        // ------------------------------------------------------------------
        phase = "D3-directed-full-rate";
        out_ready_man = 1'b1;
        base = 0;
        while (base < VEC_COUNT) begin
            send_beat(base, LAT_LIMIT);
            cov_b2b++;
            base += LANES;
        end
        drain(LAT_LIMIT * 8);
        sync_check("D3");

        // ------------------------------------------------------------------
        // D4: output backpressure -- out_ready low for long stretches while
        //     results are pending. Targets H3 (hold stable, do not drop).
        // ------------------------------------------------------------------
        phase = "D4-backpressure";
        bp_auto = 1'b0;
        base = 0;
        while (base < VEC_COUNT/2) begin
            // accept the beat with the output free ...
            out_ready_man = 1'b1;
            send_beat(base, LAT_LIMIT);
            // ... then stall the output while the result is pending. The DUT
            // must hold out_valid and `result` steady for as long as we stall.
            // We do NOT offer another beat here: a legal design may have only
            // one buffer slot, and demanding a second acceptance while blocked
            // would test capacity the spec never promised.
            out_ready_man = 1'b0;
            // Offer a DIFFERENT beat while the output is still blocked. A
            // correct design may refuse it (in_ready low) or buffer it -- both
            // are legal, and the monitor records it only if the handshake
            // actually completes. What is NOT legal is letting the new beat
            // disturb the result already waiting to be accepted. Without this,
            // a design that ignores backpressure entirely is only caught by
            // luck in the random phase.
            stage_beat(base + LANES);
            in_valid = 1'b1;
            repeat (6) begin @(posedge clk); #1; end
            in_valid = 1'b0;
            out_ready_man = 1'b1;
            @(posedge clk); #1;
            base += LANES;
        end
        drain(LAT_LIMIT * 8);
        sync_check("D4");

        // ------------------------------------------------------------------
        // D5: input gaps -- in_valid deasserted between beats. A design that
        //     latches on the wrong edge or free-runs shows up here.
        // ------------------------------------------------------------------
        phase = "D5-input-gaps";
        out_ready_man = 1'b1;
        base = 0;
        while (base < VEC_COUNT/2) begin
            send_beat(base, LAT_LIMIT);
            idle_cycles(1 + (base % 4));
            cov_idle_gap++;
            base += LANES;
        end
        drain(LAT_LIMIT * 8);
        sync_check("D5");

        // ------------------------------------------------------------------
        // D6: reset mid-stream discards in-flight work (R3). Deliberately
        //     resets while results are pending and backpressure is applied,
        //     then checks no stale beat leaks into the fresh stream.
        // ------------------------------------------------------------------
        phase = "D6-reset-midstream";
        bp_auto = 1'b0;
        out_ready_man = 1'b1;
        send_beat(17, LAT_LIMIT);          // accepted with the output free
        out_ready_man = 1'b0;              // now strand the result in flight
        @(posedge clk); #1;
        cov_reset_mid++;
        rst_n = 1'b0;
        in_valid = 1'b0;
        repeat (2) begin @(posedge clk); #1; end
        if (out_valid !== 1'b0) note_fail("out_valid survived reset (R3)");
        rst_n = 1'b1;
        out_ready_man = 1'b1;
        @(posedge clk); #1;
        if (out_valid !== 1'b0) note_fail("stale result emitted after reset (R3)");
        beats_sent = 0; beats_recv = 0;    // fresh stream
        for (int i = 0; i < MAX_BEATS; i++) avail_time[i] = -1;
        // and it must work normally afterwards
        send_beat(31, LAT_LIMIT);
        drain(LAT_LIMIT * 4);
        sync_check("D6");

        // ------------------------------------------------------------------
        // D7: sustained full-rate burst, no gaps, no backpressure
        // ------------------------------------------------------------------
        phase = "D7-sustained";
        out_ready_man = 1'b1;
        base = 0;
        while (base < VEC_COUNT) begin
            send_beat(base, LAT_LIMIT);
            base += LANES;
        end
        drain(LAT_LIMIT * 8);
        sync_check("D7");

        // ------------------------------------------------------------------
        // R1: randomised soak. Traffic pattern is re-biased every 250 beats so
        //     the design spends real time stalled on input, stalled on output,
        //     and running flat out, rather than hovering in an easy middle.
        // ------------------------------------------------------------------
        phase = "R1-soak";
        bp_auto = 1'b1;
        begin
            int w_gap;
            for (int b = 0; b < SOAK_BEATS; b++) begin
                // Re-bias every 250 beats so the design spends real time
                // input-starved, output-blocked, and flat out, instead of
                // hovering in an easy middle. bp_weight drives a FREE-RUNNING
                // generator, so out_ready keeps toggling and a capacity-1
                // design still makes progress.
                case ((b / 250) % 4)
                    0: begin w_gap = 10; bp_weight =  5; end  // mostly flat out
                    1: begin w_gap = 70; bp_weight = 10; end  // input-starved
                    2: begin w_gap = 10; bp_weight = 75; end  // output-blocked
                    3: begin w_gap = 45; bp_weight = 45; end  // both, interleaved
                endcase
                base = ($urandom_range(0, VEC_COUNT-1));
                send_beat(base, LAT_LIMIT * 16);
                if (($urandom_range(0,99)) < w_gap) begin
                    idle_cycles(1 + ($urandom_range(0,2)));
                    cov_idle_gap++;
                end
                if ((b % 97) == 96) begin
                    bp_weight = 0;
                    drain(LAT_LIMIT * 16);
                end
            end
        end
        bp_auto = 1'b0;
        out_ready_man = 1'b1;
        drain(LAT_LIMIT * 16);

        // ------------------------------------------------------------------
        phase = "final";
        idle_cycles(4);

        // ---- quality numbers: METRIC only, never gating --------------------
        $display("METRIC: beats_checked=%0d", beats_recv);
        $display("METRIC: observed_latency_cycles_min=%0d max=%0d", lat_min, lat_max);
        $display("METRIC: backpressure_cycles=%0d input_stall_cycles=%0d",
                 cov_bp, cov_in_stall);

        // ---- coverage floor: a run that never hit the hard states is not a
        //      pass, however many checks it did ----------------------------
        begin
            int cov_missing;
            cov_missing = 0;
            $display("// coverage: clamp_hi=%0d clamp_lo=%0d tie1=%0d tie2=%0d sh0=%0d sh31=%0d",
                     cov_clamp_hi, cov_clamp_lo, cov_tie1, cov_tie2, cov_sh0, cov_sh31);
            $display("// coverage: bp=%0d in_stall=%0d reset_mid=%0d idle_gap=%0d b2b=%0d",
                     cov_bp, cov_in_stall, cov_reset_mid, cov_idle_gap, cov_b2b);
            if (cov_clamp_hi  == 0) begin cov_missing++; $display("// COVERAGE HOLE: never saturated to +127"); end
            if (cov_clamp_lo  == 0) begin cov_missing++; $display("// COVERAGE HOLE: never saturated to -128"); end
            if (cov_tie1      == 0) begin cov_missing++; $display("// COVERAGE HOLE: no step-1 exact tie exercised"); end
            if (cov_tie2      == 0) begin cov_missing++; $display("// COVERAGE HOLE: no step-2 exact tie exercised"); end
            if (cov_sh0       == 0) begin cov_missing++; $display("// COVERAGE HOLE: shift==0 never exercised"); end
            if (cov_sh31      == 0) begin cov_missing++; $display("// COVERAGE HOLE: shift==31 never exercised"); end
            if (cov_bp        == 0) begin cov_missing++; $display("// COVERAGE HOLE: output backpressure never applied"); end
            if (cov_in_stall  == 0) begin cov_missing++; $display("// COVERAGE HOLE: input never stalled by in_ready"); end
            if (cov_reset_mid == 0) begin cov_missing++; $display("// COVERAGE HOLE: no mid-stream reset"); end
            if (cov_idle_gap  == 0) begin cov_missing++; $display("// COVERAGE HOLE: no idle gap between beats"); end
            if (cov_missing > 0)
                note_fail($sformatf("%0d coverage holes -- run did not exercise the target hazards",
                                    cov_missing));
        end

        if (checks < MIN_CHECKS)
            note_fail($sformatf("insufficient coverage: only %0d checks executed", checks));

        if (errors == 0)
            $display("TEST_RESULT: PASS");
        else
            $display("TEST_RESULT: FAIL: %s (%0d failing checks of %0d)",
                     fail_reason, errors, checks);
        $finish;
    end

    // global watchdog -- ~40x the expected run length
    initial begin
        #40_000_000;
        $display("// watchdog fired in phase=%s at beats_sent=%0d beats_recv=%0d",
                 phase, beats_sent, beats_recv);
        $display("TEST_RESULT: FAIL: timeout -- checker did not complete (phase=%s)", phase);
        $finish;
    end

endmodule
