#!/usr/bin/env python3
"""Emit the refs.lock file_hashes block from MEASURED closures.

The lock becomes a BUILD PRODUCT. It drifted to guarding 16 of 143 consumed
files because it was hand-maintained: nothing could tell anyone which vendored
files a task actually reads, so nothing could tell them the list was wrong.

Input is capture_refs_closure.py's JSON, which comes from Verilator's own --MMD
dependency output rather than from parsing sim_flags_verilator.txt. Those flags
are mostly `-y` search paths; d_nw03's whole vendored input is one directory,
so there is no static answer to parse.

PER-TASK ATTRIBUTION IS EMITTED ALONGSIDE THE HASH. When an anchor moves, the
first question is which task's oracle it affects, and a flat list cannot answer
it. Written as a comment per file rather than a second structure, so the lock
stays one grep away from readable.

Usage: gen_refs_lock.py <closures.json> [--write]
"""
import hashlib
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCK = os.path.join(REPO, "refs.lock")


def main(argv):
    if len(argv) < 2:
        print(__doc__.strip().split("\n")[-1], file=sys.stderr)
        return 2
    d = json.load(open(argv[1]))
    if d.get("errors"):
        n = sum(len(v) for v in d["errors"].values())
        print(f"REFUSING: {n} closure(s) failed to elaborate. A lock generated "
              f"from a partial capture records the files it happened to reach "
              f"and silently omits the rest, which is the defect it replaces.",
              file=sys.stderr)
        for t, tops in sorted(d["errors"].items()):
            for top in tops:
                print(f"  {t} / {top}", file=sys.stderr)
        return 1

    users = {}
    for task, tops in d["closures"].items():
        short = "_".join(task.split("_")[:2])
        for top, files in tops.items():
            for f in files:
                users.setdefault(f, set()).add(short)

    # REGENERATION MUST NOT LAUNDER DRIFT. A file already recorded whose bytes
    # no longer match is the one case where the lock is doing its job: the
    # mismatch IS the finding. Rewriting it from disk turns a red check green
    # and destroys the only evidence that the anchor moved, because once the
    # hashes agree the distinction is not recoverable from the record.
    #
    # refs/common_cells/src/cdc_fifo_gray.sv is exactly this. It was edited in
    # c0a5a47 on 2026-08-19 adding a .SYNC_STAGES passthrough -- deliberately,
    # with an UPSTREAM_v2 note in the same commit -- while the lock was never
    # updated. d_ca04's oracle moved under it. Three things have to be measured
    # before it is re-recorded, and none of them survives the overwrite.
    prior = dict(re.findall(r"^  (refs/\S+): \{sha256: ([0-9a-f]{64})",
                            open(LOCK, encoding="utf-8", errors="replace").read(), re.M))
    rows, missing = [], []
    for path in sorted(users):
        fp = os.path.join(REPO, path)
        if not os.path.isfile(fp):
            missing.append(path)
            continue
        b = open(fp, "rb").read()
        rows.append((path, hashlib.sha256(b).hexdigest(), len(b),
                     ",".join(sorted(users[path]))))
    if missing:
        print(f"REFUSING: {len(missing)} consumed file(s) absent from disk",
              file=sys.stderr)
        return 1

    drift = [(p, prior[p], sha) for p, sha, _n, _w in rows
             if p in prior and prior[p] != sha]
    if drift and "--accept-drift" not in argv:
        print(f"REFUSING: {len(drift)} file(s) are recorded with a DIFFERENT "
              f"hash than they now have on disk. Regenerating would overwrite "
              f"the record of a moved anchor, which is the evidence, not the "
              f"noise. Establish what changed first; pass --accept-drift only "
              f"once that is recorded elsewhere.", file=sys.stderr)
        for p, was, now in drift:
            print(f"  {p}\n    recorded {was[:16]}  on disk {now[:16]}",
                  file=sys.stderr)
        return 1

    out = ["  # GENERATED by scripts/gen_refs_lock.py from a Verilator --MMD",
           "  # capture. Do not hand-edit: an entry added by hand is a claim",
           "  # nobody measured, which is how this block came to guard 16 of the",
           "  # 143 files the tasks actually read. Trailing comment names the",
           "  # tasks whose closure contains the file.",
           f"  # {len(rows)} files, captured across "
           f"{sum(len(v) for v in d['closures'].values())} tops in "
           f"{len(d['closures'])} tasks."]
    for path, sha, n, who in rows:
        out.append(f"  {path}: {{sha256: {sha}, bytes: {n}}}   # {who}")
    block = "\n".join(out)

    if "--write" not in argv:
        print(block)
        return 0

    lock = open(LOCK, encoding="utf-8", errors="replace").read()
    m = re.search(r"^(\s*file_hashes:\s*\n)(?:  .*\n|\s*\n)*", lock, re.M)
    if not m:
        print("no file_hashes block in refs.lock", file=sys.stderr)
        return 2
    open(LOCK, "w", encoding="utf-8").write(
        lock[:m.end(1)] + block + "\n" + lock[m.end(0):])
    print(f"refs.lock file_hashes rewritten: {len(rows)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
